# Generated by Django 3.1.3 on 2021-04-29 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estate', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_address', models.CharField(max_length=100, verbose_name='house address')),
                ('active', models.BooleanField(default=False, verbose_name='active resident')),
                ('priv', models.IntegerField(default=0, verbose_name='priviledges')),
                ('is_admin', models.BooleanField(default=False, verbose_name='is Admin')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('estate', models.ManyToManyField(related_name='residents', to='estate.Estate', verbose_name='estate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resident', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
