# Generated by Django 3.1.3 on 2021-05-12 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estate', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_address', models.CharField(max_length=100, verbose_name='house address')),
                ('status', models.IntegerField(default=0, verbose_name='status')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='estate.estate', verbose_name='Estate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resident', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
