# Generated by Django 3.1.3 on 2021-04-29 16:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='estate name')),
                ('total_house', models.IntegerField(blank=True, null=True, verbose_name='total house')),
                ('street1', models.CharField(max_length=150, verbose_name='street 1')),
                ('city', models.CharField(max_length=20, verbose_name='city')),
                ('state_region', models.CharField(max_length=100, verbose_name='state or region')),
                ('country', models.CharField(max_length=100, verbose_name='country')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='comment')),
                ('admin', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='admin')),
            ],
        ),
    ]
