# Generated by Django 3.1.3 on 2021-05-02 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estate',
            options={'ordering': ['created_date']},
        ),
        migrations.RemoveField(
            model_name='estate',
            name='admin',
        ),
        migrations.AddField(
            model_name='estate',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created Date'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EstateAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perms', models.IntegerField(blank=True, null=True, verbose_name='permission')),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.estate', verbose_name='Estate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'unique_together': {('user', 'estate')},
            },
        ),
    ]
