# Generated by Django 3.1.3 on 2021-05-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estatetype',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Estate Type'),
        ),
    ]
