# Generated by Django 3.1.3 on 2021-05-02 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0002_auto_20210502_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estateadmin',
            name='estate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='estate.estate', verbose_name='Estate'),
        ),
    ]
