# Generated by Django 3.1.3 on 2021-06-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0005_auto_20210519_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Onboarding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estate', models.CharField(max_length=50, verbose_name='estate')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('attachment', models.FileField(blank=True, max_length=255, null=True, upload_to='upload/onboarding/', verbose_name='Attachement')),
            ],
        ),
    ]
