# Generated by Django 3.1.3 on 2021-06-26 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0006_onboarding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboarding',
            name='estate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='estate.estate', verbose_name=''),
        ),
    ]
