# Generated by Django 3.1.3 on 2021-06-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0007_auto_20210626_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboarding',
            name='attachment',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='upload/onboarding/'),
        ),
        migrations.AlterField(
            model_name='onboarding',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='onboarding',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
