# Generated by Django 3.1.3 on 2021-06-26 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0008_auto_20210626_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboarding',
            name='attachment',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='uploads/onboarding/'),
        ),
        migrations.AlterField(
            model_name='onboarding',
            name='estate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='estate.estate'),
        ),
    ]
