# Generated by Django 3.1.3 on 2021-07-29 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0009_auto_20210626_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onboarding',
            old_name='message',
            new_name='body',
        ),
    ]
