# Generated by Django 3.1.3 on 2021-07-29 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0010_auto_20210729_0212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onboarding',
            old_name='body',
            new_name='message',
        ),
    ]
